<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "armpackage"
 *
 * Auto generated by Extension Builder 2019-03-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Courses',
    'description' => 'Furplan academy courses',
    'category' => 'plugin',
    'author' => 'Anisur Rahaman Mullick',
    'author_email' => 'anisur.mullick@gmail.com',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
